version: "3.7"

services:
  nginx: 
    image: nginx:latest    
    restart: unless-stopped
    volumes: 
      - ./config/nginx.conf:/etc/nginx/nginx.conf     
    ports:
      - "80:80"
      - "443:443" 
    networks:
      - shiny-network

  shiny:
    image: shiny-server:fixed-6.2.23  
    restart: unless-stopped
    ports: 
      - "3838:3838"
    volumes:
      - ./config/shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - /home/shiny/logs:/var/log/shiny-server/:rw
      - /home/shiny/apps:/srv/shiny-server/apps:rw
      - /home/shiny/app_cache:/app_cache:rw
    build:
      context: ./shiny-server   
    command: ["/home/run_server.sh"]
    networks:
      - shiny-network
  
networks:
  shiny-network:
    driver: bridge
